#!/bin/bash
# /qompassai/qluv/completions/_qluv
# ---------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved
#
#compdef qluv
#autoload

_qluv_download() {
    if (( $+commands[curl] )); then
        curl -fsSL "$1"
    else
        wget -qO- "$1"
    fi
}

_qluv_extract_versions() {
    local type=$1
    qluv "list-${type}" | grep -oE '([0-9]+\.){2}[0-9]+'
}

_qluv_install() {
    local -a lua_versions
    if _cache_invalid lua_versions || ! _retrieve_cache lua_versions; then
        lua_versions=($(_qluv_download 'https://www.lua.org/ftp/' | 
            sed -n 's/.*lua-\(5\.[0-9]\.[0-9]\)\.tar\.gz.*/\1/p'))
        _store_cache lua_versions lua_versions
    fi
    compadd -a lua_versions
}

_qluv_install-luajit() {
    local -a luajit_versions
    if _cache_invalid luajit_versions || ! _retrieve_cache luajit_versions; then
        luajit_versions=($(_qluv_download 'https://luajit.org/download.html' |
            awk '/MD5 Checksums/{f=1;next} /<\/pre/{f=0} f' |
            sed -n 's/.*LuaJIT-\([0-9.]*\)\.tar\.gz.*/\1/p'))
        _store_cache luajit_versions luajit_versions
    fi
    compadd -a luajit_versions
}

_qluv_install-luarocks() {
    local -a luarocks_versions
    if _cache_invalid luarocks_versions || ! _retrieve_cache luarocks_versions; then
        luarocks_versions=($(_qluv_download 'https://luarocks.github.io/luarocks/releases/releases.json' |
            grep -o '"version":"[^"]*"' | cut -d'"' -f4))
        _store_cache luarocks_versions luarocks_versions
    fi
    compadd -a luarocks_versions
}

_qluv() {
    local context state state_descr line
    typeset -A opt_args

    _1st_arguments=(
        'install:Install the given lua version'
        'use:Switch to the given lua version'
        'set-default:Set the given version as default for lua'
        'unset-default:Unset the default lua version'
        'uninstall:Uninstall the given lua version'
        'list:List installed lua versions'
        'install-luajit:Install the given luajit version'
        'use-luajit:Switch to the given luajit version'
        'set-default-luajit:Set the given version as default for luajit'
        'unset-default-luajit:Unset the default luajit version'
        'uninstall-luajit:Uninstall the given luajit version'
        'list-luajit:List installed luajit versions'
        'install-luarocks:Install the given luarocks version'
        'use-luarocks:Switch to the given luarocks version'
        'set-default-luarocks:Set the given version as default for luarocks'
        'unset-default-luarocks:Unset the default luarocks version'
        'uninstall-luarocks:Uninstall the given luarocks version'
        'list-luarocks:List installed luarocks versions'
        'current:List present versions being used'
        'version:Display qluv version'
        'help:Display help text'
    )

    _arguments -C '*:: :->command' && return

    case $state in
        command)
            _describe -t commands 'qluv command' _1st_arguments
            ;;
        *)
            case ${words[1]} in
                install) _qluv_install ;;
                install-luajit) _qluv_install-luajit ;;
                install-luarocks) _qluv_install-luarocks ;;
                use|set-default|uninstall)
                    compadd $(_qluv_extract_versions) 
                    ;;
                use-luajit|set-default-luajit|uninstall-luajit)
                    compadd $(_qluv_extract_versions luajit)
                    ;;
                use-luarocks|set-default-luarocks|uninstall-luarocks)
                    compadd $(_qluv_extract_versions luarocks)
                    ;;
            esac
            ;;
    esac
}

_qluv "$@"

